# Generated by Django 4.2.17 on 2025-01-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0003_alter_ad_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
    ]
