# Generated by Django 5.1.4 on 2026-04-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_score_source_site'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='score',
            new_name='games_score_user_id_ec7ed9_idx',
            old_name='games_score_user_id_e63d8c_idx',
        ),
    ]
