# Generated by Django 5.1.3 on 2024-12-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='reward',
            field=models.FloatField(default=0.0),
        ),
    ]
