# Generated by Django 5.1.3 on 2024-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_score_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
