# Generated by Django 5.1.3 on 2024-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_score_tokenclaimed_claimedtokens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimedtokens',
            old_name='claimed_token',
            new_name='claimed_tokens',
        ),
        migrations.AddField(
            model_name='claimedtokens',
            name='total_tokens',
            field=models.FloatField(default=0.0),
        ),
    ]
