# Generated by Django 5.1.3 on 2024-12-11 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_rename_claimed_token_claimedtokens_claimed_tokens_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimedTokens',
            new_name='Tokens',
        ),
    ]
