# Generated by Django 5.1.3 on 2024-12-11 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_rename_claimedtokens_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
