# Generated by Django 5.1.4 on 2024-12-24 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_merkeldatastructure_tokeninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='claimed_tokens',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='score',
            name='last_claimed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='score',
            name='tokenInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tokeninfo'),
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
