# Generated by Django 5.1.4 on 2024-12-24 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_score_claimed_tokens_score_last_claimed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokeninfo',
            name='token_address',
        ),
        migrations.AddField(
            model_name='tokeninfo',
            name='bnb_contract_address',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='tokeninfo',
            name='solana_contract_address',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tokenInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tokeninfo')),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
