# Generated by Django 5.1.4 on 2024-12-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_remove_tokeninfo_token_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
