# Generated by Django 5.1.4 on 2024-12-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_delete_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='TokenInfo',
        ),
    ]
