# Generated by Django 5.1.4 on 2024-12-24 18:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_delete_game_delete_tokeninfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=100)),
                ('token_symbol', models.CharField(max_length=100)),
                ('solana_contract_address', models.CharField(max_length=700, null=True)),
                ('bnb_contract_address', models.CharField(max_length=700, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('tokens', models.FloatField(default=0.0)),
                ('claimed_tokens', models.FloatField(default=0.0)),
                ('last_claimed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tokenInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tokeninfo')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tokenInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tokeninfo'),
        ),
    ]
