# Generated by Django 5.1.4 on 2024-12-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_game_tokeninfo_score_game_tokeninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokeninfo',
            name='token_symbol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
