# Generated by Django 5.1.4 on 2024-12-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_game_created_at_game_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokeninfo',
            name='token_symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
