# Generated by Django 5.1.4 on 2024-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='started_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
