# Generated by Django 5.1.4 on 2024-12-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_brands_started_date_members_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
