# Generated by Django 5.1.4 on 2024-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_members_earned_dollar_members_earned_tokens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='earned_dollar',
            new_name='earned_dollars',
        ),
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('CEO', 'CEO'), ('devs', 'Developer'), ('product manager', 'Product Manager'), ('consultant', 'Consultant')], max_length=50),
        ),
    ]
