# Generated by Django 5.1.4 on 2025-01-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_alter_members_earned_dollars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='token_prices',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='total_tokens',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='total_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
