# Generated by Django 5.1.4 on 2025-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_brands_token_prices_brands_total_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='token_count_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='token_duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='ownership',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='role',
            field=models.CharField(choices=[('super_founder', 'Super Founder'), ('super_builder', 'Super Builder'), ('founder', 'Founder'), ('builder', 'Builder'), ('communicator', 'Communicator'), ('tourist', 'Tourist'), ('listener', 'Listener')], max_length=50),
        ),
    ]
