# Generated by Django 5.1.4 on 2025-01-06 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_brands_token_count_date_brands_token_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='tokenInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tokeninfo'),
        ),
    ]
