# Generated by Django 5.1.4 on 2025-01-09 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('super_founder', 'Super Founder'), ('super_builder', 'Super Builder'), ('founder', 'Founder'), ('builder', 'Builder'), ('communicator', 'Communicator'), ('tourist', 'Tourist'), ('listener', 'Listener')], max_length=50)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('earned_tokens', models.FloatField(blank=True, default=0.0, null=True)),
                ('earned_dollars', models.FloatField(blank=True, default=0.0, null=True)),
                ('ownership', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brands', models.ManyToManyField(blank=True, to='worlds.brand')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
