# Generated by Django 5.1.4 on 2025-01-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerkelDatastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialized_leaves', models.CharField(max_length=1000)),
                ('modified_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=100)),
                ('token_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('solana_contract_address', models.CharField(max_length=700, null=True)),
                ('bnb_contract_address', models.CharField(blank=True, max_length=700, null=True)),
                ('total_value', models.FloatField(blank=True, default=0, null=True)),
                ('total_tokens', models.FloatField(blank=True, default=0, null=True)),
                ('token_prices', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_count_date', models.DateField(blank=True, null=True)),
                ('token_duration', models.IntegerField(blank=True, default=0, null=True)),
                ('tokenInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tokens.tokeninfo')),
            ],
        ),
    ]
