# Generated by Django 5.1.4 on 2025-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokeninfo',
            name='solana_contract_address',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
